[package]
name = "forum"
version = "0.1.0"
edition = "2018"
license = "MIT OR Apache-2.0"
readme = "README.md"
repository = "https://github.com/riamundomartins/forum"
description = "Forum provides a very simple pub-sub API, based on channels."

[dependencies]

